### PR TITLE
Adding retry delay when there is a ConnectException

### PR DESCRIPTION
**Pull request by garadox**
Turbine may not be ready for connections when vizceral-hystrix has started.

### CODE REVIEW

**Comment by OskarKjellin** [comment]
I would rather do something like this:

```
.onErrorResumeNext(ex ->
                {
                    if (!(ex instanceof UnknownClusterException || ex instanceof IllegalStateException))
                    {
                        logger.error("Exception from hystrix event for cluster " + cluster + " for region " + configuration.getRegionName() + ". Will retry", ex);

                        if (ex instanceof ConnectException)
                        {
                            return Observable.timer(10, TimeUnit.SECONDS).flatMap(ignore -> read());
                        }
                        else
                        {
                            return read();
                        }
                    }
                    return Observable.error(ex);
                });
```

The issue with sleep is that it blocks the thread. In this case we only have 1 thread per core (for client and server). So if we have 1 cluster of turbine that is running and one isn't the non running will block the other with it's sleeps

**Comment by OskarKjellin** [comment]
Actually I guess we can simplify it and always wait 10 seconds before retrying. Doesn't matter if its's ConnectException or not

**Comment by garadox** [comment]
That was my original implementation - to always wait 10 seconds. I'll update the PR to the unblocking suggestion in a few minutes.

**Comment by OskarKjellin** [comment]
Released as v1.0.5

**Pull request merged**
